# HTTP Server
server:
  port: 1212   # HTTP (Tomcat) port

spring:
  application:
    name: gateway-server
#  cloud:
#    services:
#      registrationMethod: route

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

#  instance:
#
#ribbon:
#    eureka:
#        enabled: true

# Connect timeout used by Apache HttpClient
#ribbon:
#  ConnectTimeout: 3000

# Read timeout used by Apache HttpClient
#ribbon:
#  ReadTimeout:5000

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000


ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000