# HTTP Server
server:
  port: 2222   # HTTP (Tomcat) port

spring:
  application:
    name: rooms-server
  cloud:
    services:
      registrationMethod: route

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

rabbitmq:
  addresses: ${RABBITMQ_URL:amqp://guest:guest@localhost:5672}
  virtual-host: /

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000