
spring:
  application:
    name: auth-server
  datasource:
      url: jdbc:postgresql://localhost/hotel_users_db
      username: zannasapoval
      password: mypasswordforsql
      driver-class: org.postgresql.Driver

# HTTP Server
server:
  port: 8081   # HTTP (Tomcat) port
#  cloud:
#    services:
#      registrationMethod: route

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka
  instance:
    preferIpAddress: true

# Connect timeout used by Apache HttpClient
#ribbon:
#  ConnectTimeout: 3000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000