# HTTP Server
server:
  port: 4444   # HTTP (Tomcat) port

# Spring properties
spring:
  application:
    name: food-service

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka
  instance:
   leaseRenewalIntervalInSeconds: 1
   leaseExpirationDurationInSeconds: 2

ribbon:
  eureka:
    enabled: true

