
spring:
  application:
    name: bill-server

# HTTP Server
server:
  port: 3333   # HTTP (Tomcat) port

#  cloud:
#    services:
#      registrationMethod: route

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka
  instance:
    preferIpAddress: true